### ISSUE TITLE
Add examples/code for guides to GitHub

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#346] opened 2022-04-01 20:35 UTC
We have good guides on docs.conduit.io which covering different topics. It would be good to have the code for those on GitHub, so they can be more easily fetched or followed.

**Comment by neovintage** [comment] 2022-06-13 17:00
Duplicate of https://github.com/ConduitIO/conduit/issues/428

**Closed by neovintage** 2022-06-13 17:00 UTC
Labels: documentation, triage
