### ISSUE TITLE
Display the "Save Changes" button inactive

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#580] opened 2022-08-16 15:30 UTC
[Setting pipelines] Display the "Save Changes" button inactive until the name and description of the pipeline is changed.
Arguments:
Inactive "Save Changes" button is helped to understand that the user didn't put new changes
This will get rid of unnecessary sending requests to the server

**Comment by jmar910** [comment] 2022-09-21 18:53
Duplicate of #579

**Closed by jmar910** 2022-09-21 18:53 UTC
