### ISSUE TITLE
Bug: Postgres plugin fails to parse integer values larger than int16

### ISSUE THREAD

**Issue by samirketema** [ConduitIO/conduit#252] opened 2022-02-24 18:29 UTC
### Bug description

Using integer values larger than `int16` in a source pg database causes the following error in the pg plugin:
> ```github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func1\n        /app/pkg/pipeline/lifecycle.go:373\n  - error reading from source:\n    github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run.func2\n        /app/pkg/pipeline/stream/source.go:94\n  - source client read:\n    github.com/conduitio/conduit/pkg/plugins.(*sourceClient).Read\n        /app/pkg/plugins/source.go:136\n  - rpc error: code = Unknown desc = source server read: failed to assign payload: failed to parse int: strconv.ParseInt: parsing \"84721\": value out of range"```

At the time of reporting this issue, this is where the bug occurs: https://github.com/ConduitIO/conduit/blob/79c57b86c6c1f6522d7e73f04c28f5c6489de535/pkg/plugins/pg/source/handlers.go#L110

Also would be worth double checking that we support all postgres datatypes.

### Steps to reproduce

1. Create source postgres table containing int values larger than the golang type `int16`
```pgsql
pg-test=# \d samir_input;
                            Table "public.samir_input"
 Column |  Type   | Collation | Nullable |                 Default
--------+---------+-----------+----------+-----------------------------------------
 id     | bigint  |           | not null | nextval('samir_input_id_seq'::regclass)
 data   | integer |           |          |
Indexes:
    "samir_input_pkey" PRIMARY KEY, btree (id)

pg-test=# SELECT * FROM samir_input;
 id |   data
----+----------
  1 |       39
  2 |      294
  3 |      295
  4 |    28391
  5 |    84721
  6 |    84928
  7 | 89438943
  8 |    82849
  9 |   847394
 10 | 79834739
(10 rows)
```

2. Create a new pipeline, with 2 postgres connectors - one source connector reading from the input table and a destination connector pointed at the same database

3. Start the pipeline, check logs:
> ```github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func1\n        /app/pkg/pipeline/lifecycle.go:373\n  - error reading from source:\n    github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run.func2\n        /app/pkg/pipeline/stream/source.go:94\n  - source client read:\n    github.com/conduitio/conduit/pkg/plugins.(*sourceClient).Read\n        /app/pkg/plugins/source.go:136\n  - rpc error: code = Unknown desc = source server read: failed to assign payload: failed to parse int: strconv.ParseInt: parsing \"84721\": value out of range"```

### Version

v0.2.0-nightly.20220224 darwin/amd64

**Comment by lovromazgon** [comment] 2022-03-02 16:38
Duplicate of https://github.com/ConduitIO/conduit/issues/121

**Closed by lovromazgon** 2022-03-02 16:38 UTC
Labels: bug, triage, plugin:pg
