### ISSUE TITLE
Error isn't documented in Swagger

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#581] opened 2022-08-16 18:20 UTC
The error {"code":9,"message":"failed to delete pipeline: pipeline has connectors attached"} isn’t documented in [Swagger](http://localhost:8080/openapi/#/PipelineService/PipelineService_DeletePipeline)

/v1/pipelines/{id}
Request Method: DELETE
400
message: "failed to delete pipeline: pipeline has connectors attached"

**Comment by lovromazgon** [comment] 2023-03-08 16:59
Duplicate of https://github.com/ConduitIO/conduit/issues/589.

**Closed by lovromazgon** 2023-03-08 16:59 UTC
