### ISSUE TITLE
Update available connectors' list

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#991] opened 2023-04-08 12:28 UTC
### Feature description

https://github.com/ConduitIO/conduit/blob/main/docs/connectors.md

**Comment by ahmeroxa** [comment] 2023-04-25 15:53
Ideally we could have some automation scrape the list from the conduit-labs repo and generate the list

**Comment by lovromazgon** [comment] 2023-04-25 16:42
I started working on a script like that a while ago, it fetches all repos that import the SDK. The ultimate goal was to create a CI action that creates a PR every time a connector is created or released (kinda like dependabot), it adds an entry in a JSON file that lists the connectors, their versions and links to the compiled binaries. We could use that JSON file to create a simple UI for a connector registry and Conduit could then fetch that file and download connectors on demand, without the need for the user to manually download connectors.
https://github.com/lovromazgon/connector-list

**Comment by lovromazgon** [comment] 2024-01-08 15:54
Closing as duplicate of #1015

**Closed by lovromazgon** 2024-01-08 15:54 UTC
Labels: documentation
