### ISSUE TITLE
Possible race condition when a user force stops a pipeline

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1801] opened 2024-08-21 16:35 UTC
### Bug description

The following unit test reproduces this issue: https://github.com/ConduitIO/conduit/pull/1797/commits/309833b672d1da8d270ad09e7304655813f9d80c.

### Steps to reproduce

https://github.com/ConduitIO/conduit/pull/1797/commits/309833b672d1da8d270ad09e7304655813f9d80c

### Version

v0.11.0

**Comment by raulb** [comment] 2024-10-11 08:19
Closing this one. Duplicate of https://github.com/ConduitIO/conduit/issues/1891

**Closed by raulb** 2024-10-11 08:19 UTC
Labels: bug
