### ISSUE TITLE
Pipeline does not seem to stop after the stoping

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#575] opened 2022-08-16 14:29 UTC
- The user isn't informed about the error in UI after occurring the error during the data transfer process
- The user can't stop the pipeline running after the system is returned error during  the data transfer process
- After receiving any the data transfer error the new data isn't transferred to the Destination, but  the pipeline continues to run
request: /v1/pipelines/{{pipeline_id}}/stop
[video](https://www.notion.so/meroxa/bug-4f305b0629d445139d295e8518586c04#8d1a294751ae4b599bfd4e2af3811e19) -notion

**Comment by lovromazgon** [comment] 2022-10-14 18:34
Closing as duplicate of https://github.com/ConduitIO/conduit/issues/662

**Closed by lovromazgon** 2022-10-14 18:34 UTC
